### ISSUE TITLE
can't auto Merging video with ffmpeg

### ISSUE THREAD

**Issue by cjj7227** [Kallys/MediaDownloader#13]
![image](https://user-images.githubusercontent.com/29445518/34157387-4e8cb432-e4fc-11e7-91c1-c501f5ed37c8.png)

Command Line is working。

**Comment by Kallys** [comment]
Hi! Are you using latest version (v1b) published yesterday or the older one (v0) ?

**Comment by cjj7227** [comment]
Version 1.0

and older version(years ago) is working good。

**Comment by Kallys** [comment]
Ok I inspected and you are right: new caching system is blocking stream merging.
Fix is not trivial but I am working on it right now.
Thanks for your report as a beta tester!

**Comment by Kallys** [comment]
Should be fix with latest commit, can you confirm?

**Comment by cjj7227** [comment]
![image](https://user-images.githubusercontent.com/29445518/35080651-de949996-fc49-11e7-8398-87fa45175517.png)
The first download is fix, but after，when I download another video，it always show “downloading 0.0%” except the first.

**Comment by Kallys** [comment]
Ok, I think this is a side effect due to remaining file into your download folder (due to original bug).
But to prevent this in future, I added a new check in last commit (and two other bug fixes).
Please try last commit, and tell me if everything works as it should do.
Thanks a lot for your help!

**Comment by cjj7227** [comment]
![image](https://user-images.githubusercontent.com/29445518/35179828-f6088904-fddc-11e7-95f2-57daa0a575f1.png)
ok,it works,but I found it just can not download this video.....

https://www.youtube.com/watch?v=ECIU3SQyUU4

**Comment by Kallys** [comment]
I can't reproduce your issue with the given link (it works on my side).

I could suggest you to:
1) be sure you are using latest youtube-dl release (`youtube-dl -U`).
2) clean up your download folder (remove every files).
3) if issue persists, find the .log et .err files associated with your faulty download and post their content here (should be like: temp/xxxxxxxxxxxxxx.xxxxxxxx.137+251.log)

**Comment by cjj7227** [comment]
5a390054007780.51176470.217+251.err
```
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
ERROR: unable to download video data: HTTP Error 403: Forbidden
WARNING: The info failed to download, trying with "https://www.youtube.com/watch?v=ECIU3SQyUU4"
ERROR: requested format not available
```
log
```
[youtube] ECIU3SQyUU4: Downloading webpage
[youtube] ECIU3SQyUU4: Downloading video info webpage
[youtube] ECIU3SQyUU4: Extracting video information
```
youtube-dl is up-to-date (2018.01.18)
it works on the older version，same server。
![image](https://user-images.githubusercontent.com/29445518/35184069-94395d76-fe2b-11e7-98f9-841ccda45c8c.png)

**Comment by Kallys** [comment]
Does the old version of MediaDownloader and new one are on the same host and share the same ip?
Youtube-dl reports an error 403, that sounds like a network/youtube-dl issue more than a MediaDownloader issue.
Maybe you could try the following command on the server with the new version (assuming www-data is your web user):
```sudo -u www-data youtube-dl --rm-cache-dir```

**Comment by Kallys** [comment]
And try to delete the temp/5a390054007780.51176470.json too.

**Comment by cjj7227** [comment]
`[info] Available formats for ECIU3SQyUU4:

format code  extension  resolution note

249          webm       audio only DASH audio   57k , opus @ 50k, 1.29MiB
250          webm       audio only DASH audio   79k , opus @ 70k, 1.73MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 3.12MiB
171          webm       audio only DASH audio  132k , vorbis@128k, 3.08MiB
251          webm       audio only DASH audio  147k , opus @160k, 3.37MiB
160          mp4        256x144    144p  113k , avc1.4d400c, 25fps, video only, 2.56MiB
278          webm       256x144    144p  131k , webm container, vp9, 13fps, video only, 2.56MiB
133          mp4        426x240    240p  249k , avc1.4d4015, 25fps, video only, 5.54MiB
242          webm       426x240    240p  275k , vp9, 25fps, video only, 5.83MiB
243          webm       640x360    360p  482k , vp9, 25fps, video only, 10.43MiB
134          mp4        640x360    360p  640k , avc1.4d401e, 25fps, video only, 14.34MiB
244          webm       854x480    480p  885k , vp9, 25fps, video only, 18.67MiB
135          mp4        854x480    480p 1214k , avc1.4d401e, 25fps, video only, 26.84MiB
247          webm       1280x720   720p 1663k , vp9, 25fps, video only, 35.96MiB
136          mp4        1280x720   720p 2396k , avc1.4d401f, 25fps, video only, 52.71MiB
248          webm       1920x1080  1080p 2872k , vp9, 25fps, video only, 62.36MiB
137          mp4        1920x1080  1080p 4428k , avc1.640028, 25fps, video only, 98.87MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
`

there is no 217，but it request to download 217+251，so it show error 403。

Somehow，it works just now。

before
![image](https://user-images.githubusercontent.com/29445518/35184474-24861e5a-fe31-11e7-9bac-0a0de9a54190.png)

just a moment ago 

![image](https://user-images.githubusercontent.com/29445518/35184468-0fc54806-fe31-11e7-9e62-78726a7ef368.png)

**Comment by Kallys** [comment]
It's because MediaDownloader cache youtube-dl result (dump json file).
So first time you query a video, a json file will be generated into temp/ folder.
This file will only be regenerated if you delete it (I guess you did it, as I suggested to you).

Thanks a lot for you help and patience!
