### ISSUE TITLE
PHP 7.2.x: Fatal error: Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by ghost** [Kallys/MediaDownloader#15]
Attempting to run this under PHP 7.2.1 results in the following error being output into the browser when attempting to run/install the first time:

500 Internal Server Error
Fatal error: Cannot use 'Object' as class name as it is reserved

A search for the error turns up that the issue here is that that PHP 7.2 no longer allows Object to be used as a classname and quite a lot of PHP apps out there needed to fix this error to get them working again.

**Comment by Kallys** [comment]
Hi ! Thanks for your help.
I made a quick fix renaming Object class, please tell me if it works now.

**Comment by ghost** [comment]
That fix appears to work, thank you.
