### ISSUE TITLE
PHP 7.2: Install - Internal Server Error - Cannot change save handler when session is active

### ISSUE THREAD

**Issue by ghost** [Kallys/MediaDownloader#16]
I've pulled down a fresh copy of the repo after the last issue I ran into was fixed. Upon heading to my /mediadownloader/ directory, the URL redirects to /mediadownloader/public/install (as expected) and I receive the following error:

Media Downloader
Internal Server Error
session_set_save_handler(): Cannot change save handler when session is active

**Comment by Kallys** [comment]
Hmm... I can't perform test right now with php7.2.
I'm afraid too that it could be a fatfree related issue.
I'm sorry, you will need to be patient to use MediaDownloader with php7.2.

**Comment by ghost** [comment]
That's not a problem. If there's anything I can do to help, please let me know.

**Comment by nk932714** [comment]
facing the same issue

**Comment by Kallys** [comment]
Not sure if last commit solve this issue, can you confirm?
Thanks

**Comment by nk932714** [comment]
Thanks a lot fixed now

**Comment by ghost** [comment]
I can confirm this issue is no longer happening.
