### ISSUE TITLE
can't install with caddy

### ISSUE THREAD

**Issue by triaqu** [Kallys/MediaDownloader#19]
`</html>session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/MediaDownloader/sources/lib/composer/bcosca/fatfree-core/base.php:1670)
[/var/www/MediaDownloader/sources/app/lib/session.php:34] Base->clear()
[/var/www/MediaDownloader/sources/app/lib/alerter.php:39] App\Lib\Session->Clear()
[/var/www/MediaDownloader/sources/app/lib/alerter.php:41] Base->mutex()
[/var/www/MediaDownloader/temp/1pv1bcbmkkohu.3pxdgdmcml0k4.php:50] App\Lib\Alerter::GetMessages()
[/var/www/MediaDownloader/temp/1pv1bcbmkkohu.31g6l0jjtckk4.php:1] Preview->render()
[/var/www/MediaDownloader/sources/app/controllers/install.php:22] Preview->render()
[/var/www/MediaDownloader/sources/app/app.php:147] Base->run()
[index.php:7] App\App->Run()
<!DOCTYPE html>
`

**Comment by Kallys** [comment]
Please tell me which caddy version you are using.

**Comment by triaqu** [comment]
Caddy v1.0.3

**Comment by Kallys** [comment]
Ok, I just tried to install the same caddy version and it works without any issue.
Please post here your Caddyfile and tell me when this error occurs.

**Comment by triaqu** [comment]
OS  Debian 9  php 7.0

Caddyfile
mydomain:443 {
root  /var/www/MediaDownloader/public
tls  my_key my_crt
fastcgi / /var/run/php/php7.0-fpm.sock {
        ext     .php
        split   .php
        index   index.php
     }
}



'root@localhodt:/var/www/MediaDownloader# composer install
Deprecation warning: Your package name kallys/MediaDownloader is invalid, it should not contain uppercase characters. We suggest using kallys/media-downloader instead. Make sure you fix this as Composer 2.0 will error.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
root@localhost:/var/www/MediaDownloader# composer update
Deprecation warning: Your package name kallys/MediaDownloader is invalid, it should not contain uppercase characters. We suggest using kallys/media-downloader instead. Make sure you fix this as Composer 2.0 will error.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
root@localhost:/var/www/MediaDownloader# php index.php
<!DOCTYPE html>
<html>
        <head>
                <meta charset="UTF-8">
                <title>Media Downloader</title>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <link rel="stylesheet" href="http://cac/css/gfonts.css">
                <link rel="stylesheet" href="http://cac/css/bootstrap.min.css">
                <link rel="stylesheet" href="http://cac/css/font-awesome.min.css">
                <link rel="stylesheet" href="http://cac/css/main.css">


                <script type="text/javascript" src="http://cac/js/jquery-1.12.0.min.js"></script>
                <script type="text/javascript" src="http://cac/js/bootstrap.min.js"></script>
        </head>
        <body>
                <div class="navbar navbar-default">
                        <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="http://cac">Media Downloader</a>
                        </div>


                </div>

                <div class="container">
                                        </div>


<div class="container">
        <div class="panel panel-primary">
                <div class="panel-heading"><h3 class="panel-title">Installation</h3></div>
                <div class="panel-body">
                        <form method="post" class="form-horizontal">
                                                                <fieldset>
                                        <legend>Requirements</legend>
                                        <table class="table table-striped table-hover">
                                                <thead>
                                                        <tr>
                                                                <th>Name</th>
                                                                <th>Value</th>
                                                                <th>Status</th>
                                                        </tr>
                                                </thead>
                                                <tbody>
                                                                                  <tr class="text-success">
                                                                        <td>php_version</td>
                                                                        <td>7.0.33-0+deb9u5</td>
                                                                        <td>
                                                                                  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                                                                  </td>
                                                                </tr>
                                                                                  <tr class="text-success">
                                                                        <td>mdc</td>
                                                                        <td>/var/www/MediaDownloader/mdc</td>
                                                                        <td>
                                                                                  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                                                                  </td>
                                                                </tr>
                                                                                  <tr class="text-success">
                                                                        <td>logs</td>
                                                                        <td>/var/www/MediaDownloader/resources/logs/</td>
                                                                        <td>
                                                                                  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                                                                  </td>
                                                                </tr>
                                                                                  <tr class="text-success">
                                                                        <td>databases</td>
                                                                        <td>/var/www/MediaDownloader/resources/databases/</td>
                                                                        <td>
                                                                                  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                                                                  </td>
                                                                </tr>
                                                                                  <tr class="text-success">
                                                                        <td>sessions</td>
                                                                        <td>/var/www/MediaDownloader/resources/sessions/</td>
                                                                        <td>
                                                                                  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                                                                  </td>
                                                                </tr>
                                                                                  <tr class="text-success">
                                                                        <td>temp</td>
                                                                        <td>/var/www/MediaDownloader/temp/</td>
                                                                        <td>
                                                                                  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                                                                  </td>
                                                                </tr>
                                                                                  </tbody>
                                        </table>
                                </fieldset>

                                <fieldset>
                                        <legend>Administrator</legend>
                                        <p class="help-block">Administrator is a super user in charge of setting up this server.</p>
                                        <div class="form-group ">
                                                <label for="admin-name" class="col-sm-2 control-label">Name</label>
                                                <div class="col-sm-10">
                                                        <input type="text" class="form-control" id="admin-name" name="name" value="" placeholder="Administrator">
                                                                                  </div>
                                        </div>
                                        <div class="form-group ">
                                                <label for="admin-passwd" class="col-sm-2 control-label">Password</label>
                                                <div class="col-sm-10">
                                                        <input type="password" class="form-control" id="admin-passwd" name="password" value="" placeholder="Password">                                                                                  </div>
                                        </div>
                                        <div class="form-group ">
                                                <label for="admin-passwd-confirm" class="col-sm-2 control-label">Password confirmation</label>
                                                <div class="col-sm-10">
                                                        <input type="password" class="form-control" id="admin-passwd-confirm" name="password_confirm" value="" placeholder="Password confirmation">
                                                                                  </div>
                                        </div>
                                </fieldset>

                                <fieldset>
                                        <legend>Server settings</legend>
                                        <div class="form-group ">
                                                <label for="youtubedl_path" class="col-sm-2 control-label">Youtube-dl path</label>
                                                <div class="col-sm-10">
                                                        <input type="text" class="form-control" id="youtubedl_path" name="youtubedl_path" value="/usr/local/bin/youtube-dl">
                                                        <span class="help-block">Path to youtube-dl binary.</span>
                                                                                  </div>
                                        </div>
                                        <div class="form-group ">
                                                <label for="download_path" class="col-sm-2 control-label">Download path</label>
                                                <div class="col-sm-10">
                                                        <input type="text" class="form-control" id="download_path" name="download_path" value="/var/www/MediaDownloader/public/downloads/">
                                                        <span class="help-block">Path on this server where media will be downloaded to.</span>
                                                                                  </div>
                                        </div>
                                </fieldset>

                                <div class="text-center">
                                        <button type="reset" class="btn btn-default">Reset</button>
                                        <button type="submit" class="btn btn-primary">Install</button>
                                </div>
                        </form>
                </div>
        </div>
</div>




    </body>
</html>session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/MediaDownloader/sources/lib/composer/bcosca/fatfree-core/base.php:1670)
[/var/www/MediaDownloader/sources/app/lib/session.php:34] Base->clear()
[/var/www/MediaDownloader/sources/app/lib/alerter.php:39] App\Lib\Session->Clear()
[/var/www/MediaDownloader/sources/app/lib/alerter.php:41] Base->mutex()
[/var/www/MediaDownloader/temp/1pv1bcbmkkohu.3pxdgdmcml0k4.php:50] App\Lib\Alerter::GetMessages()
[/var/www/MediaDownloader/temp/1pv1bcbmkkohu.31g6l0jjtckk4.php:1] Preview->render()[/var/www/MediaDownloader/sources/app/controllers/install.php:22] Preview->render()[/var/www/MediaDownloader/sources/app/app.php:147] Base->run()
[index.php:7] App\App->Run()
<!DOCTYPE html>
<html>
        <head>
                <meta charset="UTF-8">
                <title>Media Downloader</title>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <link rel="stylesheet" href="http://cac/css/gfonts.css">
                <link rel="stylesheet" href="http://cac/css/bootstrap.min.css">
                <link rel="stylesheet" href="http://cac/css/font-awesome.min.css">
                <link rel="stylesheet" href="http://cac/css/main.css">


                <script type="text/javascript" src="http://cac/js/jquery-1.12.0.min.js"></script>
                <script type="text/javascript" src="http://cac/js/bootstrap.min.js"></script>
        </head>
        <body>
                <div class="navbar navbar-default">
                        <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="http://cac">Media Downloader</a>
                        </div>


                </div>

                <div class="container">'

**Comment by Kallys** [comment]
Ok, thanks.

Few things to progress: 
- First, run `composer install` in folder containing `composer.json` (`MediaDownloader/` not `MediaDownloader/public`)
- Then, you are not supposed to run this app in CLI mode:
Don't run `php index.php` but use your web server instead: execute `caddy` inside `MediaDownloader/public` folder
- Finally, you really shouldn't use your root user to perform all those steps (use www-data on debian)

**Comment by triaqu** [comment]
Hi.  
  Actually  I run the composer in the folder of MediaDownloader  and  running the php is because the page localhost\install not found   in the web browser.

**Comment by Kallys** [comment]
Hi, you're right `composer` should have complained about `composer.json` file if you weren't in right directory. Moreover, error logs indicate that FatFree is already installed.

Then, the next thing you need to do is to tell `caddy` that all URL should be rewrote to index.php. Moreover, you can add some logging lines if things don't go as expected:
```
mydomain:443 {
    root /var/www/MediaDownloader/public
    tls my_key my_crt
    log stdout
    errors stderr
    fastcgi / /var/run/php/php7.0-fpm.sock {
        ext .php
        split .php
        index index.php
    }
    rewrite {
        to {path} /index.php?{path}&{query}
    }
}
```

Next, if things still does not work, you can paste your `caddy` logs here (please use the "Insert code" syntax for better readability).

**Comment by triaqu** [comment]
Yes,it work.

Thank  you.
