### ISSUE TITLE
Output folder is not writable.

### ISSUE THREAD

**Issue by Qasimmodo** [Kallys/MediaDownloader#4]
Tried doing `chmod -R 775 downloads` and still getting this error.

**Comment by Kallys** [comment]
Hi ! You have to make sure downloads folder _exists_ **and** is _writable_ for web user.
Let's say your web user is _www-data_ :
1) Make sure downloads folder exists
`mkdir downloads`
2) Make www-data as group owner of the folder
`chgrp www-data downloads`
3) Make this folder writeable for group
`chmod g+rwx downloads`

If this does not solve your issue, please post the result of the following command (run in MediaDownloader folder) :
`ls -la`
