### ISSUE TITLE
Unable to download and Unable to retrieve informations for

### ISSUE THREAD

**Issue by hanarori** [Kallys/MediaDownloader#5]
problem
① click the Download button, but can not download(No error display, but can not download)
②click the Direct Download button, Display “Unable to retrieve informations for "https://www.youtube.com/watch?v=96UPCCR_s1U". Is this link correct?” error

My environment
CentOS7
Nginx 1.8.1
Python 2.7.5
Youtube-dl（https://github.com/rg3/youtube-dl）
ffmpeg version N-85836-g20e72fa Copyright (c) 2000-2017 the FFmpeg developers
php 5.4 and 7.0

→How to install?
1
/www/wwwroot/youtube.my.domain （*case）

2
The config.php file only modifies the login password and 'post_processor' => 'ffmpeg'

3
downloads folder default already exists

4 
①Youtube.my.domain folder (contains all the files inside) has all permissions 777
②Only the downloads folder and the download.php file are permissions 777 (Other files are 755 permissions)
*My web owner is www

5
is https://pic.acgnh.us/images/2017/05/05/45d6d47eb792d22b5b55afcbc91ff89b.png

What went wrong?

**Comment by Kallys** [comment]
Hum...
Something is strange in your screenshot : header display "Background downloads : / 3" while it should display "Background downloads : 0 / 3".
Which means the command line responsible of getting number of youtube-dl processes doesn't work as expected.

Do you have a shell access to your web server (through SSH for example) ?
If yes, can you post what returns the following command line:
`ps aux | grep youtube-dl | grep -v grep | grep -v \"youtube-dl -U\" | wc -l`

By the way, even for testing, it is a bad habit to set 777 permissions.
So, if www user is correctly set, you should at least set permissions to 775.

**Comment by hanarori** [comment]
[root@centos7 ~]# ps aux | grep youtube-dl | grep -v grep | grep -v \"youtube-dl -U\" | wc -l
grep: invalid option -- '"'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
0

As shown above

Well, yeah, I'll pay attention next time. Thanks for reminding me.

**Comment by Kallys** [comment]
This one went as expected, but you launched it as root.
Please try the following line (to test with your www user, adapt if needed the "www" to your web user):
`sudo -u www sh -c 'ps aux | grep youtube-dl | grep -v grep | grep -v \"youtube-dl -U\" | wc -l'`

**Comment by hanarori** [comment]
[root@centos7 www]# sudo -u www sh -c 'ps aux | grep youtube-dl | grep -v grep | grep -v \"youtube-dl -U\" | wc -l'
grep: invalid option -- '"'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
0
[root@centos7 www]# 

www users show as above

**Comment by Kallys** [comment]
Ok, seems to work.
Let's try this so (maybe shell_exec() is not allowed on your environment):
`sudo -u www php -r "var_dump(shell_exec('ps aux | grep youtube-dl | grep -v grep | grep -v \"youtube-dl -U\" | wc -l'));"`

**Comment by hanarori** [comment]
OK,Finally succeeded
It turned out that I had disabled the shell_exec PHP function
Thank you very much for your answer!

**Comment by hanarori** [comment]
Sorry, can I ask more questions?

Is about downloading video quality Best ever, video and audio are not automatically merged

Download video quality Best, video and audio it is automatically merged
But download the video quality Best ever, but not automatically merge

PS: I only installed ffmpeg
The config.php file is also changed to 'post_processor' => 'ffmpeg'

**Comment by Kallys** [comment]
Yes, currently this is not supported.
I hope to restart developing this project, but for the moment I have other priorities. Sorry!

**Comment by hanarori** [comment]
Oh, no problem
You are busy first
We can wait
Thank you for your effort.

**Comment by Kallys** [comment]
Issue with ffmpeg integration continue on #7
